---

# These tasks fix up clusters after the quota changes

- name: Fetch existing clusters
  command: kubectl get clusters.caas --all-namespaces --output json
  register: azimuth_caas_operator_list_clusters

- name: Set existing clusters fact
  set_fact:
    azimuth_caas_operator_clusters: >-
      {{-
        azimuth_caas_operator_list_clusters.stdout |
          from_json |
          json_query('items')
      }}

- name: Update variables for workstation appliances
  command: >-
    kubectl patch clusters.caas {{ azimuth_caas_operator_cluster_name }}
      --namespace {{ azimuth_caas_operator_cluster_namespace }}
      --type merge
      --patch {{ azimuth_caas_operator_cluster_patch | quote }}
  vars:
    azimuth_caas_operator_cluster_name: "{{ cluster.metadata.name }}"
    azimuth_caas_operator_cluster_namespace: "{{ cluster.metadata.namespace }}"
    azimuth_caas_operator_cluster_patch: |
      {
        "spec": {
          "extraVars": {
            "zenith_volume_size": 1
          }
        }
      }
  loop: >-
    [
      {% for cluster in azimuth_caas_operator_clusters %}
      {% if cluster.spec.clusterTypeName in ["workstation", "workstation-ssh"] %}
      {% if "zenith_volume_size" not in cluster.spec.extraVars %}
      {{ cluster | to_json }},
      {% endif %}
      {% endif %}
      {% endfor %}
    ]
  loop_control:
    loop_var: cluster
    label: "{{ cluster.metadata.namespace }}/{{ cluster.metadata.name }}"

- name: Update variables for Slurm appliances
  command: >-
    kubectl patch clusters.caas {{ azimuth_caas_operator_cluster_name }}
      --namespace {{ azimuth_caas_operator_cluster_namespace }}
      --type merge
      --patch {{ azimuth_caas_operator_cluster_patch | quote }}
  vars:
    azimuth_caas_operator_cluster_name: "{{ cluster.metadata.name }}"
    azimuth_caas_operator_cluster_namespace: "{{ cluster.metadata.namespace }}"
    azimuth_caas_operator_extravars_login_flavor: >-
      {{-
        lookup(
          'pipe',
          'openstack flavor show -f value -c id ' ~
          azimuth_caas_stackhpc_slurm_appliance_login_flavor_name
        )
      }}
    azimuth_caas_operator_extravars_control_flavor: >-
      {{-
        lookup(
          'pipe',
          'openstack flavor show -f value -c id ' ~
          azimuth_caas_stackhpc_slurm_appliance_control_flavor_name
        )
      }}
    azimuth_caas_operator_extravars_state_volume_size: >-
      {{ cluster.spec.extraVars.metrics_db_maximum_size + 10 }}
    azimuth_caas_operator_cluster_patch: |
      {
        "spec": {
          "extraVars": {
            "login_flavor": "{{ azimuth_caas_operator_extravars_login_flavor }}",
            "control_flavor": "{{ azimuth_caas_operator_extravars_control_flavor }}",
            "state_volume_size": {{ azimuth_caas_operator_extravars_state_volume_size }}
          }
        }
      }
  # This seems to be necessary because selectattr does not support nested attrs
  loop: >-
    [
      {% for cluster in azimuth_caas_operator_clusters %}
      {% if cluster.spec.clusterTypeName == "slurm" %}
      {% if "state_volume_size" not in cluster.spec.extraVars %}
      {{ cluster | to_json }},
      {% endif %}
      {% endif %}
      {% endfor %}
    ]
  loop_control:
    loop_var: cluster
    label: "{{ cluster.metadata.namespace }}/{{ cluster.metadata.name }}"
