---

# The K9s repo
k9s_repo: https://github.com/derailed/k9s
# The K9s version to download
k9s_version: v0.50.16
# The OS variant and architecture to use
# See https://github.com/derailed/k9s/releases for the available options
k9s_os: "{{ ansible_system }}"
k9s_architecture: "{{ 'amd64' if ansible_architecture == 'x86_64' else ansible_architecture }}"
# The name of the K9s archive
k9s_archive_name: "k9s_{{ k9s_os }}_{{ k9s_architecture }}.tar.gz"
# The URL of the K9s archive to download
k9s_archive_url: "{{ k9s_repo }}/releases/download/{{ k9s_version }}/{{ k9s_archive_name }}"

# The directory into which the K9s archive should be unpacked
k9s_unpack_directory: "/opt/k9s/{{ k9s_version }}"
# The directory into which the K9s binary should be placed
k9s_bin_directory: /usr/local/bin
